blogsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')), 
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    #path('', views.list_posts, name='index'),
    path('', views.ListPost.as_view(), name='index'),
    #path('<int:post_id>/', views.detail_post, name='detail'),
    path('<int:pk>/', views.DetailPost.as_view(), name='detail'),
    #path('create/', views.create_post, name='create'),
    path('create/', views.CreatePost.as_view(), name='create'),
    #path('update/<int:post_id>/', views.update_post, name='update'),
    path('update/<int:pk>/', views.UpdatePost.as_view(), name='update'),
    #path('delete/<int:post_id>/', views.delete_post, name='delete'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('categories/', views.CategoryListView.as_view(), name='categories'),
    path('categories/<int:category_id>', views.detail_category, name='detail-category'),
    path('categories/create', views.CategoryCreateView.as_view(), name='create-category'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

posts/models.py
from django.db import models
from django.conf import settings

class Category(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    game_type = models.CharField(max_length=255)
    description = models.TextField()
    #posts = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.game_type} by {self.author}'

class Game(models.Model):
    name = models.CharField(max_length = 60)

    def __str__(self):
        return f'{self.name}'

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE) #autor
    title = models.CharField(max_length=60) #título
    text = models.TextField() #conteúdo
    post_date = models.DateTimeField(auto_now=True)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return f'"{self.title}" - {self.game}'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.text} - {self.author.username}'

staticpages/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'text',
            'game',
        ]
        labels = {
            'title': 'Título',
            'text': 'Texto',
            'game': 'Jogo',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
        }

posts/views.py
from this import d
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm
from django.views import generic

# def detail_post(request, post_id):
#     post = get_object_or_404(Post, pk=post_id)
#     context = {'post': post, 'game': post.game}
#     return render(request, 'posts/detail.html', context)

# def list_posts(request):
#     post_list = Post.objects.all()
#     context = {'post_list': post_list}
#     return render(request, 'posts/index.html', context)

# def update_post(request, post_id):
#     post = get_object_or_404(Post, pk=post_id)

#     if request.method == "POST":
#         form = PostForm(request.POST)
#         if form.is_valid():
#             post.title = form.cleaned_data['title']
#             post.text = form.cleaned_data['text'] # Renderizado com a tag 'safe' no HTML
#             post.game = form.cleaned_data['game']
#             post.save()
#             return HttpResponseRedirect(
#                 reverse('posts:detail', args=(post.id, )))

#     else:
#         form = PostForm(
#             initial={
#                 'title': post.title,
#                 'text': post.text,
#                 'game': post.game
#             }
#         )
#     context = {'post': post, 'form': form}
#     return render(request, 'posts/update.html', context)

# def delete_post(request, post_id):
#     post = get_object_or_404(Post, pk=post_id)

#     if request.method == "POST":
#         post.delete()
#         return HttpResponseRedirect(reverse('posts:index'))

#     context = {'post': post}
#     return render(request, 'posts/delete.html', context)

class CreatePost(generic.CreateView):
    model = Post
    template_name = 'posts/create.html'
    fields = ['author', 'title', 'text', 'game', 'categories']
    success_url = reverse_lazy('posts:index')

class DetailPost(generic.DetailView):
    model = Post
    template_name = 'posts/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class ListPost(generic.ListView):
    model = Post
    template_name = 'posts/index.html'

class UpdatePost(generic.UpdateView):
    model = Post
    template_name = 'posts/update.html'
    fields = ['author', 'title', 'text', 'game', 'categories']
    success_url = reverse_lazy('posts:index')

class DeletePost(generic.DeleteView):
    model = Post
    template_name = 'posts/delete.html'
    success_url = reverse_lazy('posts:index')


def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'posts/comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'posts/categories.html'

class CategoryCreateView(generic.CreateView):
    model = Category
    template_name = 'posts/create_category.html'
    fields = ['author', 'game_type', 'description']
    success_url = reverse_lazy('posts:categories')

def detail_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    context = {'category': category}
    return render(request, 'posts/detail_category.html', context)

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

posts/templates/posts/categories.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias de Jogos</h2>

<section>
    <section class="lista-de-cards">
        {% for category in category_list %}
        <article class="card">
            <a href="{% url 'posts:detail-category' category.id%}"> {{ category.game_type }} </a>
        </article>
        {% endfor %}
    </section>

    <a href="{% url 'posts:create-category' %}"><button>Crie sua Categoria</button></a>
</section>

{% endblock content %}

posts/templates/posts/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar Postagem "{{ post.title }}"</h2>

<form action="{% url 'posts:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'posts:detail' post.id %}">Voltar para a postagem</a></p>
{% endblock content %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Post</h2>
<form method="POST" action="{% url 'posts:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

posts/templates/posts/create_category.html
{% extends 'base.html' %}

{% block title %}
Criar Categoria
{% endblock title %}

{% block content %}
<h2>Criar Categoria</h2>

<form action="{% url 'posts:create-category' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'posts:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar a postagem "{{ post.title }}"?
    </p>
    <button type="submit">Apagar</button>
</form>

<p><a href="{% url 'posts:detail' post.id %}">Voltar para a postagem</a></p>

{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }}
{% endblock title %}

{% block content %}
<h2> {{ post.title }} </h2>
<h5> {{ post.game }} </h5>
<h5> Author: {{ post.author }} </h5>

<section class="dados-de-filme">
    <ul>
        <li>{{ post.text|safe }}</li>
        <li><a href="{% url 'posts:update' post.id %}">Editar</a></li>
        <li><a href="{% url 'posts:delete' post.id %}">Apagar</a></li>
        <br>
        {% if post.categories.all %}
            <li>Incluso nas categorias: </li>
            <ul>
            {% for category in post.categories.all %}
                <li><a href="{% url 'posts:detail-category' category.id %}"> {{ category.game_type }}</a> </li>
            {% endfor %}
            </ul>
        {% endif %}
    </ul>
</section>

<hr>

<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if post.comment_set.all %}
            {% for comment in post.comment_set.all reversed %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <figcaption>—{{ comment.author }}, {{ comment.date|date:"D d M Y H:i:s e"}}
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhum comentário para este post.</p>
        {% endif %}
    </ul>
    
    <hr>

    <a href="{% url 'posts:comment' post.pk %}"><button>Adicione um Comentário</button></a>
</section>

{% endblock content %}

posts/templates/posts/detail_category.html
{% extends 'base.html' %}

{% block title %}
{{ category.game_type }}
{% endblock title %}

{% block content %}
<h2> {{ category.game_type }} </h2>

<section class="dados-de-filme">
    <ul>
        <li>{{ category.description|safe }}</li>
    </ul>
</section>

<hr>

<article>
    <div class="lista-de-cards">
        {% for post in category.post_set.all %}
        <div class="card">
            <a href="{% url 'posts:detail' post.id %}">{{ post.title }} </a>
            <p><h6>{{ post.post_date|date:"D d M Y H i s e"}}</h6></p>
            <p>{{ post.game }}</p>
        </div>
        {% endfor %}
    </div>
</article>

{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Posts</h2>
<section>
    <p>Não encontrou o que buscava? <a href="{% url 'posts:create' %}">Adicionar Novo Post</a></p>
</section>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <a href="{% url 'posts:detail' post.id %}"> {{ post.title }} </a>
        <p><h6>{{ post.post_date|date:"D d M Y H i s e"}}</h6></p>
        <p>{{ post.game }}</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados da Postagem {{ post.name }}</h2>
<form method="POST" action="{% url 'posts:update' post.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
<p>Esta aplicação foi desenvolvida como uma avaliação da disciplina de PMR3304 - Sistemas de Informação (2022).</p>
<p>É um blog/fórum de jogos, no qual é possível adicionar, ler, criar e atualizar postagens para jogos distintos.</p>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Play this Game!</i></h1>
<p>A Página para Comunidade Resenhadora de Jogos</p>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Play this Game!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> 
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.svg' %}" width="400px"> </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'posts:index' %}">Postagens</a></li>
                <li><a href="{% url 'posts:categories' %}">Categorias</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>
    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>&copy Copyright 2022</small>
        </p>
    </footer>
</body>

</html>